global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: 'apigateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8222']
  - job_name: 'configserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8888']
  - job_name: 'eurekaserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8761']
  - job_name: 'authservice'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:9191']
  - job_name: 'userservice'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8084']
  - job_name: 'foodservice'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8081']
  - job_name: 'orderservice'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8083']
  - job_name: 'paymentservice'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8085']
