
---
server:
  port: 8082
  url: http://localhost
---
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/order_database
    username: root
    password: tuantuan123
